name: "Setup Codee Analyzer & Formatter"
description: "Setup Codee Analyzer & Formatter"
author: "Igor S. Gerasimov"

runs:
  using: composite
  steps:
    - name: Check platform compability
      if: ${{ !(runner.os == 'Windows' && runner.arch == 'X64') || (runner.os == 'Linux' && (runner.arch == 'X64' || runner.arch == 'ARM64')) }}
      shell: bash
      run: |
        echo "Not supported combination of OS & Arch: ${{ runner.os }} & ${{ runner.arch }}"
        exit 1
