name: "Setup Codee Analyzer & Formatter"
description: "Setup Codee Analyzer & Formatter"
author: "Igor S. Gerasimov"

runs:
  using: composite
  steps:
    - name: Check platform compability
      if: ${{ !(runner.os == 'Windows' && runner.arch == 'X64') || (runner.os == 'Linux' && (runner.arch == 'X64' || runner.arch == 'ARM64')) }}
      shell: bash
      run: |
        echo "Not supported combination of OS & Arch: ${{ runner.os }} & ${{ runner.arch }}"
        exit 1

    - name: Match runner platform with Codee artifact
      id: mapping
      shell: bash
      run: |
        case "${{ runner.os }}-${{ runner.arch }} in
          "Windows-X64")
            archive_name=windows-amd64
            archive_extension=zip
            ;;
          "Linux-X64")
            archive_name=linux-x86_64
            archive_extension=tar.gz
            ;;
          "Linux-ARM64")
            archive_name=linux-aarch64
            archive_extension=tar.gz
            ;;
          *)
            exit 1
            ;;
        esac

        echo "codee_archive=${archive_name}" >> $GITHUB_OUTPUT
        echo "codee_archive_extension=${archive_extension}" >> $GITHUB_OUTPUT
