name: "Setup Codee"
description: "Setup Codee Analyzer & Formatter"
author: "Igor S. Gerasimov"

runs:
  using: composite
  steps:
    - name: Check platform compability
      if: ${{ !((runner.os == 'Windows' && runner.arch == 'X64') || (runner.os == 'Linux' && (runner.arch == 'X64' || runner.arch == 'ARM64'))) }}
      shell: bash
      run: |
        echo "Not supported combination of OS & Arch: ${{ runner.os }} & ${{ runner.arch }}"
        exit 1

    - name: Match runner platform with Codee artifact
      id: mapping
      shell: bash
      run: |
        case "${{ runner.os }}-${{ runner.arch }}" in
          "Windows-X64")
            archive_name=windows-amd64
            archive_extension=zip
            ;;
          "Linux-X64")
            archive_name=linux-x86_64
            archive_extension=tar.gz
            ;;
          "Linux-ARM64")
            archive_name=linux-aarch64
            archive_extension=tar.gz
            ;;
          *)
            exit 1
            ;;
        esac

        echo "codee_archive=${archive_name}" >> $GITHUB_OUTPUT
        echo "codee_archive_extension=${archive_extension}" >> $GITHUB_OUTPUT

    - name: Download Codee artifact
      shell: bash
      run: |
        curl -L -o /tmp/codee.${{ steps.mapping.outputs.codee_archive_extension }} https://codee.com/release/codee-2025.3.5-${{ steps.mapping.outputs.codee_archive }}.${{ steps.mapping.outputs.codee_archive_extension }}

    - name: Extract Codee artifact
      shell: bash
      run: |
        if [[ "${{ steps.mapping.outputs.codee_archive_extension }}" == "zip" ]]; then
          unzip -qq /tmp/codee.zip -d /tmp/codee-tmp
          mv /tmp/codee-tmp/* /tmp/codee/
          rm -rf /tmp/codee-tmp
        else
          mkdir -p /tmp/codee/
          tar --strip-components=1 -xzf /tmp/codee.tar.gz  -C /tmp/codee
        fi

    - name: Add Codee binaries to PATH
      shell: bash
      run: echo "/tmp/codee/bin" >> $GITHUB_PATH
